### ISSUE TITLE
web 密码如有特殊字符将无法登录

### ISSUE THREAD

**Issue by lh11117** [ravizhan/yangcong-dl#6]
如图，报错了，但是我的账号密码是输入正确的

![image](https://github.com/ravizhan/yangcong-dl/assets/99455215/bcf005e2-90d0-4dda-b549-5428a1bb82fc)

```
Traceback (most recent call last):
  File "D:\Programs\Python38\lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Programs\Python38\lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Programs\Python38\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Programs\Python38\lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "D:\Python代码\yangcong-dl-main\web.py", line 36, in login
    yangcong = webapi.YCForWeb(0, int(mode), a, b)
  File "D:\Python代码\yangcong-dl-main\webapi.py", line 29, in __init__
    if self.authorization is not None:
AttributeError: 'YCForWeb' object has no attribute 'authorization'
127.0.0.1 - - [19/Feb/2024 12:58:07] "GET /loginget?mode=1&a=账号&b=密码 HTTP/1.1" 500 -    #这里a和b分别是我的账号密码，因为隐私问题，我隐藏了
```

但是 authorization 可以正常登陆

**Comment by Catc326** [comment]
能用啊，你再看看仔细readme

**Comment by lh11117** [comment]
我发现是因为我的密码里有特殊字符，例如`+`，它在YCForWeb.login中被转换为了` ` (空格)

**Comment by ravizhan** [comment]
收到，已确认问题所在，将尽快修复

**Comment by lh11117** [comment]
@ravizhan  我已经修复了问题，有一个pr: #7 ，请看一下

**Comment by fsf678** [comment]
你好，感谢你对本项目的支持！**该BUG已修复**。
请原谅我们学业繁重只能在周末进行修复。PS: 本人测试该BUG时，发现yangcong官网一个及其严重的漏洞，原因也是跟我一样没有使用encodeURIComponent，导致了修改密码时不能使用特殊字符，并且将自动删除它。
